name: Mac Cloud Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Apple Dependencies
        run: brew install ldid dpkg make

      - name: Install Theos Compiler & SDKs (Safe Method)
        run: |
          export THEOS=$HOME/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          curl -LO https://github.com/theos/sdks/archive/refs/heads/master.zip
          unzip -q master.zip
          mv sdks-master/* $THEOS/sdks/
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Compile Mod Menu (FORCED MAC PATH)
        run: make package FINALPACKAGE=1 THEOS=$HOME/theos

      - name: Upload Finished Mod Menu
        uses: actions/upload-artifact@v4
        with:
          name: Animal-Company-Mod-Menu
          path: |
            **/*.dylib
            **/*.deb
            packages/*.deb
